# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
DISABLE_LINTERS:
  # A self-contained maintaince page is not expected to conform to best
  # practices for web site.
  - HTML_DJLINT
  # Pylint errors on missing dependencies, and is redundant with ruff.
  - PYTHON_PYLINT
  # Pyright errors on missing dependencies.
  - PYTHON_PYRIGHT
  # Disable dependency security scanning.
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  # Link checking more likely to cause false positives than be useful for us.
  - SPELL_LYCHEE
DISABLE_ERRORS_LINTERS:
  # There's no easy local feedback loop for spelling issues before
  # pushing, so keep them non-blocking to avoid unnecessary PR cycles
  # for words that just need adding to the dictionary.
  - SPELL_CSPELL
GITHUB_COMMENT_REPORTER: false
GITHUB_STATUS_REPORTER: true
