# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

[project]
name = "cdn-maintenance-toggle"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "boto3",
    "botocore",
    "python-dotenv",
    "trieregex",
]

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py312"
# For linting only; not intended for `ruff format`.
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "G", "I", "ANN"]

[dependency-groups]
dev = [
    "black",
    "isort",
    "mypy",
    "ruff",
    "types-boto3",
]

[[tool.mypy.overrides]]
module = ["trieregex.*"]
follow_untyped_imports = true
