---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: License Header Check

"on": [pull_request]

permissions:
  contents: read

jobs:
  license-header-check:
    name: License Header Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Check License Headers
        run: |
          ./check-headers.sh
